branch-defaults:
  master:
    environment: bucketlist
environment-defaults:
  bucketlist:
    branch: null
    repository: null
global:
  application_name: bucketlist
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.5
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
